-- cities snafran with FK
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities (
id INT UNIQUE AUTO_INCREMENT PRIMARY KEY, state_id INT NOT NULL FOREIGN KEY,
name VARCHAR(256) NOT NULL);
